#!/usr/bin/env python3
"""agent-progress local checkpoint tool (v2). Standard library only: no network, no credentials.

Model: immutable checkpoint snapshots + authoritative HEAD.json (atomic replace) +
expected-HEAD compare-and-swap + per-project exclusive lock. CURRENT.md and INDEX.md
are derived views generated by this tool. Hashes detect accidental change; they are
not signatures.

Commands (every command accepts --root; default $AGENT_PROGRESS_ROOT or /home/user/agent-progress):
  list                         projects with status / HEAD / revision
  resume     --project D/P     compact hand-over brief (integrity + first action + pending + lint)
  read       --project D/P     full HEAD checkpoint JSON (strict chain check)
  state      --project D/P     HEAD state JSON only (starting point for a full rewrite)
  update     --project D/P --expected ID --patch FILE|- --note TEXT [--dry-run]
  checkpoint --project D/P --expected ID|NEW --state FILE|- --note TEXT [--merge-parent ID]
  validate   [--project D/P] [--deep] [--verify-local --workspace DIR]
  rebuild                      regenerate every CURRENT.md and INDEX.md
"""
import argparse
import copy
import datetime
import hashlib
import json
import os
import re
import sys
import uuid
from pathlib import Path

SCHEMA_VERSION = 1
DEFAULT_ROOT = Path(os.environ.get('AGENT_PROGRESS_ROOT') or '/home/user/agent-progress')

REQUIRED_KEYS = ('title', 'status', 'goal', 'constraints', 'completed', 'pending', 'decisions',
                 'artifacts', 'evidence', 'risks', 'next_actions', 'avoid', 'sync', 'handoff',
                 'related_projects')
OPTIONAL_KEYS = ('context',)
STATE_KEYS = set(REQUIRED_KEYS)  # kept for backward compatibility with older importers
LIST_KEYS = ('constraints', 'completed', 'pending', 'decisions', 'artifacts', 'evidence', 'risks',
             'next_actions', 'avoid', 'related_projects')
STATUSES = {'IN_PROGRESS', 'READY_FOR_REVIEW', 'COMPLETED', 'BLOCKED', 'LOCAL_READY_PENDING_SYNC', 'PAUSED'}
DEPRECATED_STATUSES = {'LOCAL_READY_PENDING_SYNC'}
SECRET_KEYS = {'password', 'passphrase', 'token', 'secret', 'api_key', 'access_token',
               'authorization_header', 'private_key'}
SECRET_RE = re.compile(
    r'gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|AKIA[A-Z0-9]{16}'
    r'|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|Bearer\s+[A-Za-z0-9._~+/-]{20,}'
    r'|sk-ant-[A-Za-z0-9_-]{20,}|sk-proj-[A-Za-z0-9_-]{20,}|AIza[0-9A-Za-z_-]{35}'
    r'|xox[abprs]-[0-9A-Za-z-]{10,}|glpat-[0-9A-Za-z_-]{20,}')
SLUG = re.compile(r'^[a-z0-9][a-z0-9-]{0,63}$')
CID = re.compile(r'^\d{8}T\d{6}Z-[a-f0-9]{12}$')
STATE_HARD_LIMIT = 65536
STATE_SOFT_LIMIT = 49152
HANDOFF_SOFT_KEYS = 15
RESUME_HANDOFF_KEYS = ('waiting_for', 'current_request_type', 'user_question', 'last_actor')
PATCH_OPS = ('set', 'unset', 'remove', 'upsert', 'append')


class HandoffError(Exception):
    pass


# ---------------------------------------------------------------- basic IO

def now():
    return datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')


def dump(x):
    """Canonical bytes. Checkpoint hashes depend on this exact format: do not change."""
    return (json.dumps(x, ensure_ascii=False, sort_keys=True, indent=2) + '\n').encode()


def digest(data):
    return hashlib.sha256(data).hexdigest()


def load(p):
    return json.loads(Path(p).read_text(encoding='utf-8'))


def load_input(src):
    """Read JSON from a path, or from stdin when src is '-'."""
    text = sys.stdin.read() if str(src) == '-' else Path(src).read_text(encoding='utf-8')
    return json.loads(text)


def atomic(p, data):
    p = Path(p)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_name('.' + p.name + '.' + uuid.uuid4().hex + '.tmp')
    try:
        fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, 'wb') as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, p)
        try:  # best-effort directory flush for durable renames where supported
            fd = os.open(p.parent, os.O_RDONLY)
            os.fsync(fd)
            os.close(fd)
        except OSError:
            pass
    finally:
        if tmp.exists():
            tmp.unlink()


def safe_relative(relative):
    p = Path(relative)
    if p.is_absolute() or '..' in p.parts or not str(relative).strip():
        raise HandoffError('Expected a safe relative path')
    return p


def inside(root, relative):
    p = safe_relative(relative)
    out = (Path(root) / p).resolve()
    if not out.is_relative_to(Path(root).resolve()):
        raise HandoffError('Path escapes allowed root')
    return out


def project_dir(root, project):
    parts = str(project).split('/')
    if len(parts) != 2 or not all(SLUG.fullmatch(x) for x in parts):
        raise HandoffError('Project must be domain/project-id using lowercase ASCII slugs')
    return inside(root, 'projects/' + project)


def project_id(p):
    return p.parent.name + '/' + p.name


# ---------------------------------------------------------------- state rules

def check_secret(x, path='state'):
    if isinstance(x, dict):
        for k, v in x.items():
            if str(k).lower() in SECRET_KEYS:
                raise HandoffError('Secret-bearing field forbidden at ' + path + '.' + str(k))
            check_secret(v, path + '.' + str(k))
    elif isinstance(x, list):
        for i, v in enumerate(x):
            check_secret(v, path + '[' + str(i) + ']')
    elif isinstance(x, str) and SECRET_RE.search(x):
        raise HandoffError('Potential plaintext credential detected at ' + path + ' (value redacted)')


def validate_state(s):
    if not isinstance(s, dict):
        raise HandoffError('State must be a JSON object')
    missing = [k for k in REQUIRED_KEYS if k not in s]
    unknown = sorted(set(s) - set(REQUIRED_KEYS) - set(OPTIONAL_KEYS))
    if missing or unknown:
        raise HandoffError('State keys must match the template (missing: ' + ','.join(missing) +
                           '; unknown: ' + ','.join(unknown) + '); put domain details under "context"')
    for k in ('title', 'goal'):
        if not isinstance(s[k], str) or not s[k].strip():
            raise HandoffError('Missing text: ' + k)
    if s['status'] not in STATUSES:
        raise HandoffError('Unsupported project status')
    for k in LIST_KEYS:
        if not isinstance(s[k], list):
            raise HandoffError(k + ' must be an array')
    for k in ('sync', 'handoff'):
        if not isinstance(s[k], dict):
            raise HandoffError(k + ' must be an object')
    if 'context' in s and not isinstance(s['context'], dict):
        raise HandoffError('context must be an object')
    check_secret(s)
    evidence = set()
    for e in s['evidence']:
        if not isinstance(e, dict) or not all(e.get(k) for k in ('id', 'kind', 'source', 'scope')):
            raise HandoffError('Evidence requires id/kind/source/scope')
        if e['id'] in evidence:
            raise HandoffError('Duplicate evidence ID')
        evidence.add(e['id'])
    for e in s['completed']:
        if not isinstance(e, dict) or not e.get('item') or not e.get('evidence'):
            raise HandoffError('Completed item requires evidence references')
        if not isinstance(e['evidence'], list) or not set(e['evidence']).issubset(evidence):
            raise HandoffError('Completed item cites unknown evidence')
    ids = set()
    for a in s['artifacts']:
        if not isinstance(a, dict) or not a.get('id') or not a.get('role'):
            raise HandoffError('Artifact requires id and role')
        if a['id'] in ids:
            raise HandoffError('Duplicate artifact ID')
        ids.add(a['id'])
        if a.get('availability') not in {'LOCAL', 'REMOTE_ONLY', 'LOCAL_AND_REMOTE'}:
            raise HandoffError('Invalid artifact availability')
        if not re.fullmatch(r'[a-f0-9]{64}', str(a.get('sha256', ''))):
            raise HandoffError('Artifact requires SHA256')
        if a['availability'] != 'REMOTE_ONLY' and not a.get('local_path'):
            raise HandoffError('Local artifact needs local_path')
        if a.get('local_path'):
            safe_relative(a['local_path'])
        if a['availability'] != 'LOCAL' and not a.get('remote'):
            raise HandoffError('Remote artifact needs recovery locator')
    for r in s['related_projects']:
        if not isinstance(r, str) or len(r.split('/')) != 2 or not all(SLUG.fullmatch(x) for x in r.split('/')):
            raise HandoffError('Invalid related project ID')
    if not s['handoff'].get('first_action') or not isinstance(s['handoff'].get('running_operations'), list):
        raise HandoffError('Handoff requires first_action and running_operations')
    if len(dump(s)) > STATE_HARD_LIMIT:
        raise HandoffError('Keep current state below 64KiB: write a compact checkpoint (the parent '
                           'checkpoint already is the immutable full archive)')


def lint_state(s):
    """Advisory warnings for the current state. They never block a write."""
    out = []
    size = len(dump(s))
    if size > STATE_SOFT_LIMIT:
        out.append(f'state is {size // 1024} KiB (hard limit 64 KiB): compact it; keep active goal/constraints/'
                   'pending/recent decisions and set context.compacted_from to the parent checkpoint ID')
    if len(s['handoff']) > HANDOFF_SOFT_KEYS:
        out.append(f"handoff has {len(s['handoff'])} keys: keep first_action/running_operations/waiting_for/"
                   'current_request_type there and move domain details into "context"')
    if s['status'] == 'COMPLETED' and s['pending']:
        out.append(f"status COMPLETED but {len(s['pending'])} pending item(s) remain")
    if s['status'] in {'IN_PROGRESS', 'READY_FOR_REVIEW', 'BLOCKED'} and not s['pending'] and not s['next_actions']:
        out.append('active project has neither pending items nor next_actions')
    if s['status'] in DEPRECATED_STATUSES:
        out.append('status LOCAL_READY_PENDING_SYNC is deprecated: sync state comes from progress_sync.py status')
    if 'memory' in s['sync']:
        out.append('sync.memory only describes the moment of writing (a checkpoint cannot record its own push); '
                   'use progress_sync.py status for the real sync state')
    for i, item in enumerate(s['pending']):
        if isinstance(item, dict) and not (item.get('id') and (item.get('done_when') or item.get('acceptance'))):
            out.append(f'pending[{i}] lacks id or done_when')
        elif isinstance(item, str):
            out.append(f'pending[{i}] is free text: use {{id, action, blocked_by, done_when}}')
    return out


# ---------------------------------------------------------------- checkpoint chain

def checked_head(p):
    try:
        head = load(p / 'HEAD.json')
    except FileNotFoundError:
        raise HandoffError('No HEAD.json for project ' + project_id(p)) from None
    if set(head) != {'schema_version', 'checkpoint_id', 'sha256', 'revision'} or head['schema_version'] != SCHEMA_VERSION:
        raise HandoffError('Invalid HEAD schema')
    if not CID.fullmatch(str(head['checkpoint_id'])):
        raise HandoffError('Invalid checkpoint ID')
    try:
        data = (p / 'checkpoints' / (head['checkpoint_id'] + '.json')).read_bytes()
    except FileNotFoundError:
        raise HandoffError('HEAD checkpoint file missing: ' + head['checkpoint_id']) from None
    if digest(data) != head['sha256']:
        raise HandoffError('HEAD checkpoint hash mismatch')
    cp = json.loads(data)
    if cp.get('checkpoint_id') != head['checkpoint_id'] or cp.get('revision') != head['revision']:
        raise HandoffError('HEAD identity/revision mismatch')
    return head, cp


def _check_shape(p, cp, content):
    cid = cp.get('checkpoint_id')
    if not isinstance(cid, str) or not CID.fullmatch(cid):
        raise HandoffError('Invalid checkpoint ID')
    if cp.get('schema_version') != SCHEMA_VERSION:
        raise HandoffError('Unsupported checkpoint schema')
    if cp.get('project') != p.name or cp.get('domain') != p.parent.name:
        raise HandoffError('Cross-project checkpoint detected')
    parents = cp.get('parents')
    if not isinstance(parents, list) or len(parents) > 2:
        raise HandoffError('Invalid parents')
    if len({q.get('checkpoint_id') for q in parents}) != len(parents):
        raise HandoffError('Duplicate parent')
    if not isinstance(cp.get('revision'), int):
        raise HandoffError('Invalid revision')
    if content:
        validate_state(cp['state'])
        check_secret(cp.get('note', ''), 'note')


def walk_chain(p, head_cp, deep=False, allow_missing=False):
    """Iterative (no recursion limit) walk over every reachable parent.

    Structure, identity, parent SHA256 and revision monotonicity are checked for the whole
    chain. Full content rules run on head_cp only; ancestors were validated when written and
    are protected by the hash chain. deep=True also re-checks ancestor content and reports
    problems as advisories (history is immutable, so they cannot be "fixed" in place).
    Returns (seen, missing, advisories)."""
    seen, missing, advisories = {}, [], []
    active = set()
    stack = [(head_cp, False)]
    while stack:
        cp, expanded = stack.pop()
        cid = cp['checkpoint_id']
        if expanded:
            revs = [seen[q['checkpoint_id']]['revision'] for q in cp['parents'] if q['checkpoint_id'] in seen]
            if len(revs) == len(cp['parents']) and cp['revision'] != max(revs, default=0) + 1:
                raise HandoffError('Non-monotonic revision')
            active.discard(cid)
            seen[cid] = cp
            continue
        if cid in seen:
            continue
        if cid in active:
            raise HandoffError('Checkpoint cycle detected')
        is_head = cp is head_cp
        _check_shape(p, cp, content=is_head)
        if deep and not is_head:
            try:
                _check_shape(p, cp, content=True)
            except HandoffError as e:
                advisories.append(cid + ': ' + str(e))
        active.add(cid)
        stack.append((cp, True))
        for q in cp['parents']:
            qid = q.get('checkpoint_id')
            if not isinstance(qid, str) or not CID.fullmatch(qid):
                raise HandoffError('Unsafe parent ID')
            if qid in seen:
                continue
            if qid in active:
                raise HandoffError('Checkpoint cycle detected')
            path = p / 'checkpoints' / (qid + '.json')
            if not path.exists():
                if allow_missing:
                    if qid not in missing:
                        missing.append(qid)
                    continue
                raise HandoffError('Missing parent checkpoint ' + qid + ': restore the full chain from the same '
                                   'remote commit (a normal git clone has it); do not treat as remote loss')
            data = path.read_bytes()
            if digest(data) != q.get('sha256'):
                raise HandoffError('Parent checkpoint hash mismatch')
            parent = json.loads(data)
            if parent.get('checkpoint_id') != qid:
                raise HandoffError('Parent identity mismatch')
            stack.append((parent, False))
    return seen, missing, advisories


def chain(p, headcp):
    """Strict chain check (backward-compatible API). Returns {checkpoint_id: checkpoint}."""
    return walk_chain(p, headcp)[0]


# ---------------------------------------------------------------- derived views

ITEM_FIELDS = {
    'completed': [('item', None), ('evidence', '证据')],
    'pending': [('task', None), ('action', None), ('next_action', '下一步'), ('blocked_by', '阻塞'),
                ('done_when', '完成判据'), ('acceptance', '验收')],
    'decisions': [('decision', None), ('text', None), ('source', '来源'), ('by', '决定者'), ('date', '日期'),
                  ('scope', '范围'), ('supersedes', '取代')],
    'evidence': [('kind', None), ('scope', None), ('source', '来源'), ('limitations', '局限')],
    'artifacts': [('role', None), ('local_path', '本地'), ('availability', '可用性'), ('sha256', 'sha256'),
                  ('remote', '远端')],
    'next_actions': [('action', None), ('priority', '优先级'), ('requires_user', '需用户')],
    'risks': [('risk', None), ('mitigation', '缓解')],
    'constraints': [('constraint', None), ('source', '来源')],
    'avoid': [('action', None), ('reason', '原因')],
    'running_operations': [('purpose', None), ('started_at', '启动'), ('job', '作业'), ('output', '输出')],
}


def _inline(v):
    if isinstance(v, str):
        return v.replace('\n', ' ')
    return json.dumps(v, ensure_ascii=False, sort_keys=True)


def render_item(key, item):
    if not isinstance(item, dict):
        return _inline(item)
    head = f"**[{item['id']}]** " if isinstance(item.get('id'), (str, int)) else ''
    main, labeled, used = [], [], {'id'}
    for field, label in ITEM_FIELDS.get(key, []):
        if field not in item:
            continue
        used.add(field)
        val = item[field]
        if field == 'sha256' and isinstance(val, str):
            text = val[:12] + '…'
        elif field == 'remote' and isinstance(val, dict):
            repo = val.get('repository', '')
            commit = str(val.get('commit') or val.get('last_verified_commit') or '')[:10]
            text = repo + ('@' + commit if commit else '') + (':' + val['path'] if val.get('path') else '')
            rest = {k: val[k] for k in sorted(val) if k not in {'repository', 'commit', 'last_verified_commit', 'path'}}
            text = (text or '') + (' ' + _inline(rest) if rest else '')
        elif isinstance(val, bool):
            text = '是' if val else '否'
        elif isinstance(val, list):
            text = ', '.join(_inline(x) for x in val)
        else:
            text = _inline(val)
        if label is None:
            main.append(text)
        else:
            labeled.append(label + '：' + text)
    out = head + ' — '.join(main)
    if labeled:
        out += '（' + '；'.join(labeled) + '）'
    rest = {k: item[k] for k in sorted(item) if k not in used}
    if rest:
        out += ' 〔' + json.dumps(rest, ensure_ascii=False, sort_keys=True) + '〕'
    return out.strip() or json.dumps(item, ensure_ascii=False, sort_keys=True)


def _list_section(title, key, items):
    lines = ['## ' + title, '']
    lines += ['- ' + render_item(key, x) for x in items] or ['无。']
    return lines + ['']


def _json_section(title, value):
    return ['## ' + title, '', '```json', json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2), '```', '']


def current_bytes(cp):
    s = cp['state']
    h = s['handoff']
    lines = ['# ' + s['title'], '',
             '> 派生视图（handoff.py 生成，勿手改）；权威来源为 HEAD.json 指向的不可变检查点。'
             '本检查点是否已推送以 `progress_sync.py status` 为准。', '',
             f"- 项目：`{cp['domain']}/{cp['project']}` · 状态：**{s['status']}** · revision {cp['revision']}",
             f"- 检查点：`{cp['checkpoint_id']}` · 更新：{cp['updated_at']}",
             f"- 本次变化：{_inline(cp['note'])}", '',
             '## 接手第一步', '', _inline(h.get('first_action', ''))]
    for k, label in (('waiting_for', '等待'), ('current_request_type', '当前请求类型'), ('user_question', '待用户回答')):
        if h.get(k):
            lines.append(f'- {label}：{_inline(h[k])}')
    lines.append('')
    lines += ['## 目标', '', _inline(s['goal']), '']
    lines += _list_section('未完成', 'pending', s['pending'])
    lines += _list_section('下一步', 'next_actions', s['next_actions'])
    lines += _list_section('运行中的任务（接手先确认是否仍在运行）', 'running_operations', h.get('running_operations', []))
    lines += _list_section('当前约束', 'constraints', s['constraints'])
    lines += _list_section('不要重复的错误', 'avoid', s['avoid'])
    lines += _list_section('决定与纠正', 'decisions', s['decisions'])
    lines += _list_section('已完成（附证据）', 'completed', s['completed'])
    lines += _list_section('风险', 'risks', s['risks'])
    lines += _list_section('文件与恢复位置', 'artifacts', s['artifacts'])
    lines += _list_section('证据及其边界', 'evidence', s['evidence'])
    lines += _json_section('同步记录（写入时，非实时）', s['sync'])
    rest = {k: h[k] for k in sorted(h) if k not in {'first_action', 'running_operations', 'waiting_for',
                                                     'current_request_type', 'user_question'}}
    if rest:
        lines += _json_section('交接细节', rest)
    if s.get('context'):
        lines += _json_section('领域上下文（context）', s['context'])
    lines += _list_section('关联项目', 'related_projects', s['related_projects'])
    return ('\n'.join(lines).rstrip('\n') + '\n').encode()


def all_projects(root):
    return sorted(p.parent for p in (Path(root) / 'projects').glob('*/*/HEAD.json'))


INDEX_ROW = re.compile(r'^- .* — `([a-z0-9-]+/[a-z0-9-]+)` — ')


def retained_index_rows(root):
    rows = {}
    path = Path(root) / 'INDEX.md'
    if path.exists():
        for line in path.read_text(encoding='utf-8').splitlines():
            match = INDEX_ROW.match(line)
            if match:
                rows[match.group(1)] = line
    return rows


def index_bytes(root):
    # Keep remote-only navigation rows in a deliberately partial workspace: they are not
    # validated project states; read their HEAD before acting on them.
    rows = retained_index_rows(root)
    for p in all_projects(root):
        h, cp = checked_head(p)
        ident = project_id(p)
        link = p.relative_to(Path(root)).as_posix() + '/CURRENT.md'
        rows[ident] = (f"- [{cp['state']['title']}]({link}) — `{ident}` — **{cp['state']['status']}** — "
                       f"`{h['checkpoint_id']}` — {str(cp.get('updated_at', ''))[:10]}")
    lines = ['# 跨模型进度索引', '',
             '先读 GLOBAL.md 与 LOCATION.json，只打开相关方向。接手某项目：'
             '`python3 agent-progress-skill/scripts/handoff.py resume --project <方向>/<项目ID>`。',
             'CURRENT.md 是派生视图，以校验后的 HEAD 检查点为准；同步状态用 `progress_sync.py status` 查看。', '',
             '实际项目进度默认私有。各项目素材库的同步不等于本进度库已同步。', '']
    domain = None
    for ident, line in sorted(rows.items()):
        current = ident.split('/')[0]
        if current != domain:
            domain = current
            lines += ['## ' + domain, '']
        lines.append(line)
    return ('\n'.join(lines) + '\n').encode()


def rebuild(root):
    for p in all_projects(root):
        _, cp = checked_head(p)
        chain(p, cp)
        atomic(p / 'CURRENT.md', current_bytes(cp))
    atomic(Path(root) / 'INDEX.md', index_bytes(root))


# ---------------------------------------------------------------- writes

def checkpoint(root, project, state, expected, note, merge_parent=None):
    validate_state(state)
    check_secret(note, 'note')
    if not isinstance(note, str) or not note.strip():
        raise HandoffError('A note describing the actual change is required')
    p = project_dir(root, project)
    p.mkdir(parents=True, exist_ok=True)
    lock = p / '.write.lock'
    try:
        fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError:
        raise HandoffError('Project is locked; inspect owner/time before recovery; no automatic lock stealing') from None
    try:
        with os.fdopen(fd, 'wb') as f:
            f.write(dump({'pid': os.getpid(), 'created_at': now(), 'expected': expected}))
            f.flush()
            os.fsync(f.fileno())
        parents, rev = [], 0
        if (p / 'HEAD.json').exists():
            h, old = checked_head(p)
            chain(p, old)
            if expected != h['checkpoint_id']:
                raise HandoffError('Stale expected HEAD: reread and reconcile before writing')
            parents = [{'checkpoint_id': h['checkpoint_id'], 'sha256': h['sha256']}]
            rev = h['revision']
        elif expected != 'NEW':
            raise HandoffError('New project requires --expected NEW')
        if merge_parent:
            if not parents or not CID.fullmatch(merge_parent) or merge_parent == parents[0]['checkpoint_id']:
                raise HandoffError('Invalid merge parent')
            try:
                raw = (p / 'checkpoints' / (merge_parent + '.json')).read_bytes()
            except FileNotFoundError:
                raise HandoffError('Merge parent checkpoint missing') from None
            other = json.loads(raw)
            if other.get('checkpoint_id') != merge_parent:
                raise HandoffError('Merge parent identity mismatch')
            _check_shape(p, other, content=False)
            chain(p, other)
            parents.append({'checkpoint_id': merge_parent, 'sha256': digest(raw)})
            rev = max(rev, other['revision'])
        cid = datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ') + '-' + uuid.uuid4().hex[:12]
        domain, ident = project.split('/')
        cp = {'schema_version': SCHEMA_VERSION, 'checkpoint_id': cid, 'parents': parents, 'revision': rev + 1,
              'domain': domain, 'project': ident, 'updated_at': now(), 'note': note, 'state': state}
        data = dump(cp)
        dest = p / 'checkpoints' / (cid + '.json')
        dest.parent.mkdir(exist_ok=True)
        # Immutable exclusive creation, fsync, then atomic authoritative HEAD.
        with dest.open('xb') as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        h = {'schema_version': SCHEMA_VERSION, 'checkpoint_id': cid, 'sha256': digest(data), 'revision': rev + 1}
        atomic(p / 'HEAD.json', dump(h))
        # Render from the re-parsed bytes so the view never depends on caller key order.
        atomic(p / 'CURRENT.md', current_bytes(json.loads(data)))
        atomic(Path(root) / 'INDEX.md', index_bytes(root))
        return h
    finally:
        lock.unlink(missing_ok=True)


def _resolve(state, path, create=False):
    """Return (container_dict, last_key) for a dotted path like 'handoff.waiting_for'."""
    if not isinstance(path, str) or not path or any(not part for part in path.split('.')):
        raise HandoffError('Invalid patch path: ' + repr(path))
    parts = path.split('.')
    if parts[0] not in REQUIRED_KEYS and parts[0] not in OPTIONAL_KEYS:
        raise HandoffError('Patch path outside the state schema: ' + parts[0])
    node = state
    for part in parts[:-1]:
        if part not in node and create:
            node[part] = {}
        node = node.get(part) if isinstance(node, dict) else None
        if not isinstance(node, dict):
            raise HandoffError('Patch path does not lead to an object: ' + path)
    return node, parts[-1]


def _list_at(state, path):
    node, key = _resolve(state, path)
    value = node.get(key)
    if not isinstance(value, list):
        raise HandoffError('Patch list operation needs an array at: ' + path)
    return value


def _matches(item, selector):
    return item == selector or (isinstance(item, dict) and item.get('id') == selector)


def apply_patch(state, patch):
    """Apply a small, explicit patch. Order: set -> unset -> remove -> upsert -> append.
    set:    {"dotted.path": value}           replace/create a value
    unset:  ["dotted.path", ...]             delete keys inside objects
    remove: {"list.path": [id-or-string]}    drop items by "id" (objects) or exact equality
    upsert: {"list.path": [{"id": ...}]}     replace the item with the same id in place, else append
    append: {"list.path": [item, ...]}       add items at the end"""
    if not isinstance(patch, dict) or not patch:
        raise HandoffError('Patch must be a non-empty JSON object')
    unknown = sorted(set(patch) - set(PATCH_OPS))
    if unknown:
        raise HandoffError('Unknown patch operation(s): ' + ','.join(unknown) + '; allowed: ' + ','.join(PATCH_OPS))
    shapes = {'set': dict, 'unset': list, 'remove': dict, 'upsert': dict, 'append': dict}
    for op, kind in shapes.items():
        if op in patch and not isinstance(patch[op], kind):
            raise HandoffError(f'patch.{op} must be a JSON ' + ('object' if kind is dict else 'array'))
    for op in ('remove', 'upsert', 'append'):
        for path, value in (patch.get(op) or {}).items():
            if not isinstance(value, list):
                raise HandoffError(f'patch.{op}[{path!r}] must be an array')
    s = copy.deepcopy(state)
    for path, value in (patch.get('set') or {}).items():
        node, key = _resolve(s, path, create=True)
        node[key] = copy.deepcopy(value)
    for path in patch.get('unset') or []:
        node, key = _resolve(s, path)
        if '.' not in path:
            raise HandoffError('Top-level keys cannot be unset; set them to an empty value instead: ' + path)
        node.pop(key, None)
    for path, selectors in (patch.get('remove') or {}).items():
        items = _list_at(s, path)
        for sel in selectors:
            before = len(items)
            items[:] = [x for x in items if not _matches(x, sel)]
            if len(items) == before:
                raise HandoffError(f'remove: nothing matched {sel!r} in {path}')
    for path, new_items in (patch.get('upsert') or {}).items():
        items = _list_at(s, path)
        for new in new_items:
            if not isinstance(new, dict) or new.get('id') in (None, ''):
                raise HandoffError('upsert items must be objects with an "id"')
            for i, old in enumerate(items):
                if isinstance(old, dict) and old.get('id') == new['id']:
                    items[i] = copy.deepcopy(new)
                    break
            else:
                items.append(copy.deepcopy(new))
    for path, new_items in (patch.get('append') or {}).items():
        _list_at(s, path).extend(copy.deepcopy(new_items))
    return s


def update(root, project, patch, expected, note, dry_run=False):
    p = project_dir(root, project)
    h, cp = checked_head(p)
    if expected != h['checkpoint_id']:
        raise HandoffError('Stale expected HEAD: reread and reconcile before writing')
    new_state = apply_patch(cp['state'], patch)
    validate_state(new_state)
    if new_state == cp['state']:
        raise HandoffError('Patch produces no change; no empty checkpoint')
    changed = sorted(k for k in set(new_state) | set(cp['state']) if new_state.get(k) != cp['state'].get(k))
    if dry_run:
        return {'dry_run': True, 'would_write_revision': h['revision'] + 1, 'changed_keys': changed,
                'state_bytes': len(dump(new_state)), 'lint': lint_state(new_state),
                'changes': {k: new_state.get(k) for k in changed}}
    return dict(checkpoint(root, project, new_state, expected, note), changed_keys=changed, lint=lint_state(new_state))


# ---------------------------------------------------------------- reads

def validate(root, project=None, workspace=None, deep=False):
    out = {'pass': True,
           'scope': 'Local checkpoint integrity (whole chain) and optional local artifact hashes only; '
                    'not remote freshness, semantic approval or complete secret detection',
           'projects': []}
    paths = [project_dir(root, project)] if project else all_projects(root)
    if not paths:
        raise HandoffError('No project checkpoints found')
    for p in paths:
        h, cp = checked_head(p)
        seen, _, advisories = walk_chain(p, cp, deep=deep)
        warnings, verified = [], []
        if not (p / 'CURRENT.md').exists() or (p / 'CURRENT.md').read_bytes() != current_bytes(cp):
            warnings.append('CURRENT.md missing/stale; run rebuild')
        orphans = [z.stem for z in (p / 'checkpoints').glob('*.json') if z.stem not in seen]
        if orphans:
            warnings.append('Unreferenced checkpoints require review: ' + ','.join(sorted(orphans)))
        if (p / '.write.lock').exists():
            warnings.append('Project lock exists; inspect active writer before editing')
        if workspace:
            for a in cp['state']['artifacts']:
                if a['availability'] == 'REMOTE_ONLY':
                    continue
                f = inside(workspace, a['local_path'])
                if not f.is_file() or digest(f.read_bytes()) != a['sha256']:
                    raise HandoffError('Missing/changed local artifact: ' + a['id'] + ' in ' + project_id(p))
                verified.append(a['id'])
        entry = {'project': project_id(p), 'head': h, 'checkpoints_checked': len(seen),
                 'local_artifacts_verified': verified, 'warnings': warnings, 'lint': lint_state(cp['state'])}
        if deep:
            entry['ancestor_advisories'] = advisories
        out['projects'].append(entry)
    out['unloaded_projects'] = sorted(set(retained_index_rows(root)) - {project_id(p) for p in all_projects(root)})
    out['index_current'] = (Path(root) / 'INDEX.md').exists() and (Path(root) / 'INDEX.md').read_bytes() == index_bytes(root)
    return out


def resume_text(root, project):
    p = project_dir(root, project)
    h, cp = checked_head(p)
    seen, missing, _ = walk_chain(p, cp, allow_missing=True)
    s = cp['state']
    hd = s['handoff']
    lines = [f"# 接手简报：{s['title']}", '',
             f"项目 `{project}` · 状态 **{s['status']}** · 检查点 `{h['checkpoint_id']}` · rev {h['revision']} · 更新 {cp['updated_at']}",
             f"最近变化：{_inline(cp['note'])}"]
    integrity = f'完整性：HEAD 指纹通过；父链已校验 {len(seen)} 个检查点'
    if missing:
        integrity += f'；本地缺 {len(missing)} 个祖先（未校验，属本地恢复不完整，不代表远端丢失）'
    lines.append(integrity)
    if (p / '.write.lock').exists():
        lines.append('⚠ 存在写锁 .write.lock：先核实是否有进行中的写入，工具不会自动抢锁')
    if not (p / 'CURRENT.md').exists() or (p / 'CURRENT.md').read_bytes() != current_bytes(cp):
        lines.append('⚠ CURRENT.md 过时：运行 rebuild（派生视图，不影响 HEAD）')
    lines += ['', '## 接手第一步', _inline(hd.get('first_action', ''))]
    for k in RESUME_HANDOFF_KEYS:
        if hd.get(k):
            lines.append(f'- {k}: {_inline(hd[k])}')
    lines += ['', '## 目标', _inline(s['goal'])]

    def block(title, key, items, limit=None, newest=False):
        chosen = items[-limit:] if (limit and newest) else (items[:limit] if limit else items)
        more = len(items) - len(chosen)
        out = ['', f'## {title}（{len(items)}）'] + ['- ' + render_item(key, x) for x in chosen]
        if more > 0:
            out.append(f'- …另有 {more} 项，见 CURRENT.md / read')
        return out if items else ['', f'## {title}', '无。']

    lines += block('未完成', 'pending', s['pending'])
    lines += block('下一步', 'next_actions', s['next_actions'])
    lines += block('运行中的任务（先确认是否仍在运行）', 'running_operations', hd.get('running_operations', []))
    lines += block('当前约束', 'constraints', s['constraints'])
    lines += block('不要重复的错误', 'avoid', s['avoid'])
    lines += block('最近决定', 'decisions', s['decisions'], limit=8, newest=True)
    lines += block('最近完成', 'completed', s['completed'], limit=5, newest=True)
    lines += block('风险', 'risks', s['risks'], limit=5)
    lines += ['', f"产物 {len(s['artifacts'])} 项、证据 {len(s['evidence'])} 项：见 CURRENT.md；"
                  '本地素材核验用 validate --verify-local。']
    lint = lint_state(s)
    if lint:
        lines += ['', '## 提示（不阻断）'] + ['- ' + x for x in lint]
    scripts = Path(__file__).resolve().parent
    root_arg = '' if Path(root).resolve() == DEFAULT_ROOT.resolve() else f' --root {root}'
    lines += ['', '## 写入本项目', '先把补丁写到 /tmp/patch.json（规范见 references/state-schema.md），然后：',
              f"python3 {scripts / 'handoff.py'}{root_arg} update --project {project} "
              f"--expected {h['checkpoint_id']} --patch /tmp/patch.json --note '本次实际变化及证据' [--dry-run]",
              f"python3 {scripts / 'progress_sync.py'}{root_arg} --token-file /tmp/.gh_token push "
              f"--project {project} -m '{project}: 变化摘要'"]
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------- CLI

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--root', type=Path, default=DEFAULT_ROOT)
    sub = ap.add_subparsers(dest='command', required=True)
    sub.add_parser('list')
    sub.add_parser('rebuild')
    for name in ('read', 'resume', 'state'):
        c = sub.add_parser(name)
        c.add_argument('--project', required=True)
    sub.choices['read'].add_argument('--allow-missing-parents', action='store_true',
                                     help='report locally missing ancestors instead of failing (reading only)')
    c = sub.add_parser('checkpoint')
    c.add_argument('--project', required=True)
    c.add_argument('--expected', required=True)
    c.add_argument('--state', required=True, help='state JSON file, or - for stdin')
    c.add_argument('--note', required=True)
    c.add_argument('--merge-parent')
    u = sub.add_parser('update')
    u.add_argument('--project', required=True)
    u.add_argument('--expected', required=True)
    u.add_argument('--patch', required=True, help='patch JSON file, or - for stdin')
    u.add_argument('--note', required=True)
    u.add_argument('--dry-run', action='store_true')
    v = sub.add_parser('validate')
    v.add_argument('--project')
    v.add_argument('--deep', action='store_true', help='also re-check ancestor content (advisory)')
    v.add_argument('--verify-local', action='store_true')
    v.add_argument('--workspace', type=Path, default=Path('/home/user'))
    a = ap.parse_args(argv)
    try:
        if a.command == 'resume':
            sys.stdout.write(resume_text(a.root, a.project))
            return 0
        if a.command == 'read':
            p = project_dir(a.root, a.project)
            _, result = checked_head(p)
            _, missing, _ = walk_chain(p, result, allow_missing=a.allow_missing_parents)
            if missing:
                print(f'warning: {len(missing)} ancestor checkpoint(s) missing locally; chain only partly verified',
                      file=sys.stderr)
        elif a.command == 'state':
            p = project_dir(a.root, a.project)
            _, cp = checked_head(p)
            chain(p, cp)
            result = cp['state']
        elif a.command == 'checkpoint':
            state = load_input(a.state)
            h = checkpoint(a.root, a.project, state, a.expected, a.note, a.merge_parent)
            result = dict(h, lint=lint_state(state))
        elif a.command == 'update':
            result = update(a.root, a.project, load_input(a.patch), a.expected, a.note, a.dry_run)
        elif a.command == 'rebuild':
            rebuild(a.root)
            result = {'rebuilt': True}
        elif a.command == 'validate':
            result = validate(a.root, a.project, a.workspace if a.verify_local else None, a.deep)
        else:
            result = []
            for p in all_projects(a.root):
                h, cp = checked_head(p)
                result.append({'project': project_id(p), 'title': cp['state']['title'], 'status': cp['state']['status'],
                               'head': h['checkpoint_id'], 'revision': h['revision'], 'updated_at': cp['updated_at']})
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0
    except (HandoffError, OSError, ValueError, KeyError, TypeError) as e:
        # Never echo input state or caught raw data, which may contain secrets.
        print('Handoff failed: ' + (str(e) if isinstance(e, HandoffError) else type(e).__name__), file=sys.stderr)
        return 1
    except Exception as e:  # noqa: BLE001 - last-resort guard without leaking data
        print('Handoff failed unexpectedly: ' + type(e).__name__, file=sys.stderr)
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
